src/com/bookstore/entity/BookOrder.java
package com.bookstore.entity;
// Generated May 22, 2018 5:46:15 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BookOrder generated by hbm2java
 */
@Entity
@Table(name = "book_order", catalog = "bookstoredb")
@NamedQueries({@NamedQuery(name = "BookOrder.findAll", query = "SELECT bo FROM BookOrder bo ORDER BY bo.orderDate DESC"), 
	@NamedQuery(name = "BookOrder.countAll", query = "SELECT COUNT(bo) FROM BookOrder bo"), @NamedQuery(name = "BookOrder.findByCustomer", query = "SELECT bo FROM BookOrder bo WHERE bo.customer.customerId =:customerId ORDER BY bo.orderDate DESC"), @NamedQuery(name = "BookOrder.findByIdAndCustomer", query = "SELECT bo FROM BookOrder bo WHERE bo.orderId =:orderId AND bo.customer.customerId =:customerId")})
public class BookOrder implements java.io.Serializable {

    private Integer orderId;
    private Customer customer;
    private Date orderDate;
    private String addressLine1;
    private String addressLine2;
    private String firstname;
    private String lastname;
    private String phone;
    private String city;
    private String state;
    private String zipcode;
    private String country;
    private String paymentMethod;

    private float total;
    private float subtotal;
    private float shippingFee;
    private float tax;

    private String status;

    private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public BookOrder() {
    }

    @Column(name = "r_address_line2", nullable = false, length = 256)
    public String getAddressLine2() {
        return addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    @Column(name = "r_lastname", nullable = false, length = 30)
    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @Column(name = "r_phone", nullable = false, length = 15)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "r_city", nullable = false, length = 32)
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "r_state", nullable = false, length = 45)
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "r_zipcode", nullable = false, length = 24)
    public String getZipcode() {
        return zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Column(name = "r_country", nullable = false, length = 4)
    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Transient
    public String getCountryName() {
        return new Locale("", this.country).getDisplayCountry();
    }

    @Column(name = "subtotal", nullable = false, precision = 12, scale = 0)
    public float getSubtotal() {
        return subtotal;
    }

    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }

    @Column(name = "shipping_fee", nullable = false, precision = 12, scale = 0)
    public float getShippingFee() {
        return shippingFee;
    }

    public void setShippingFee(float shippingFee) {
        this.shippingFee = shippingFee;
    }

    @Column(name = "tax", nullable = false, precision = 12, scale = 0)
    public float getTax() {
        return tax;
    }

    public void setTax(float tax) {
        this.tax = tax;
    }

    public BookOrder(Customer customer, Date orderDate, String shippingAddress, String recipientName, String recipientPhone, String paymentMethod, float total, String status) {
        this.customer = customer;
        this.orderDate = orderDate;
        this.addressLine1 = shippingAddress;
        this.firstname = recipientName;
        this.phone = recipientPhone;
        this.paymentMethod = paymentMethod;
        this.total = total;
        this.status = status;
    }

    public BookOrder(Customer customer, Date orderDate, String shippingAddress, String recipientName, String recipientPhone, String paymentMethod, float total, String status, Set<OrderDetail> orderDetails) {
        this.customer = customer;
        this.orderDate = orderDate;
        this.addressLine1 = shippingAddress;
        this.firstname = recipientName;
        this.phone = recipientPhone;
        this.paymentMethod = paymentMethod;
        this.total = total;
        this.status = status;
        this.orderDetails = orderDetails;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "order_id", unique = true, nullable = false)
    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "customer_id", nullable = false)
    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "order_date", nullable = false, length = 19)
    public Date getOrderDate() {
        return this.orderDate;
    }

    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }

    @Column(name = "r_address_line1", nullable = false, length = 256)
    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    @Column(name = "r_firstname", nullable = false, length = 30)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Column(name = "payment_method", nullable = false, length = 20)
    public String getPaymentMethod() {
        return this.paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    @Column(name = "total", nullable = false, precision = 12, scale = 0)
    public float getTotal() {
        return this.total;
    }

    public void setTotal(float total) {
        this.total = total;
    }

    @Column(name = "status", nullable = false, length = 20)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "bookOrder", cascade = CascadeType.ALL, orphanRemoval = true)
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }

    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

    @Transient
    public int getBookCopies() {
        int total = 0;

        for (OrderDetail orderDetail : orderDetails) {
            total += orderDetail.getQuantity();
        }

        return total;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        BookOrder other = (BookOrder) obj;
        if (orderId == null) {
            if (other.orderId != null) return false;
        } else if (!orderId.equals(other.orderId)) return false;
        return true;
    }


}

src/com/bookstore/entity/Customer.java
package com.bookstore.entity;
// Generated May 22, 2018 5:46:15 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "bookstoredb", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@NamedQueries({@NamedQuery(name = "Customer.findAll", query = "SELECT c FROM Customer c ORDER BY c.registerDate DESC"), @NamedQuery(name = "Customer.findByEmail", query = "SELECT c FROM Customer c WHERE c.email = :email"), @NamedQuery(name = "Customer.countAll", query = "SELECT COUNT(c.email) FROM Customer c"), @NamedQuery(name = "Customer.checkLogin", query = "SELECT c FROM Customer c WHERE c.email = :email AND c.password = :pass")})
public class Customer implements java.io.Serializable {

    private Integer customerId;
    private String email;
    private String firstname;
    private String lastname;
    private String addressLine1;
    private String addressLine2;
    private String city;
    private String state;
    private String country;
    private String phone;
    private String zipcode;
    private String password;
    private Date registerDate;
    private Set<Review> reviews = new HashSet<Review>(0);
    private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

    public Customer() {
    }

    public Customer(String email, String firstname, String lastname, String address1, String address2, String city, String state, String country, String phone, String zipcode, String password, Date registerDate) {
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.addressLine1 = address1;
        this.addressLine2 = address2;
        this.city = city;
        this.state = state;
        this.country = country;
        this.phone = phone;
        this.zipcode = zipcode;
        this.password = password;
        this.registerDate = registerDate;
    }

    public Customer(String email, String firstname, String lastname, String address1, String address2, String city, String state, String country, String phone, String zipcode, String password, Date registerDate, Set<Review> reviews, Set<BookOrder> bookOrders) {
        this(email, firstname, lastname, address1, address2, city, state, country, phone, zipcode, password, registerDate);
        this.reviews = reviews;
        this.bookOrders = bookOrders;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "customer_id", unique = true, nullable = false)
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name = "email", unique = true, nullable = false, length = 64)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "firstname", nullable = false, length = 30)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Transient
    public String getFullname() {
        return this.firstname + " " + this.lastname;
    }

    @Column(name = "lastname", nullable = false, length = 30)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }


    @Column(name = "address_line1", nullable = false, length = 128)
    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String address1) {
        this.addressLine1 = address1;
    }

    @Column(name = "address_line2", nullable = false, length = 128)
    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String address2) {
        this.addressLine2 = address2;
    }

    @Column(name = "city", nullable = false, length = 32)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "state", nullable = false, length = 45)
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "country", nullable = false, length = 4)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Transient
    public String getCountryName() {
        return new Locale("", this.country).getDisplayCountry();
    }

    @Column(name = "phone", nullable = false, length = 15)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "zipcode", nullable = false, length = 24)
    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Column(name = "password", nullable = false, length = 16)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "register_date", nullable = false, length = 19)
    public Date getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
    public Set<Review> getReviews() {
        return this.reviews;
    }

    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
    public Set<BookOrder> getBookOrders() {
        return this.bookOrders;
    }

    public void setBookOrders(Set<BookOrder> bookOrders) {
        this.bookOrders = bookOrders;
    }

}

src/com/bookstore/controller/admin/customer/CreateCustomerServlet.java
package com.bookstore.controller.admin.customer;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.CustomerServices;

@WebServlet("/admin/create_customer")
public class CreateCustomerServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    public CreateCustomerServlet() {
        super();
    }

    protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        CustomerServices customerServices = new CustomerServices(request, response);
        customerServices.createCustomer();
    }

}

src/com/bookstore/controller/admin/customer/DeleteCustomerServlet.java
package com.bookstore.controller.admin.customer;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.CustomerServices;

@WebServlet("/admin/delete_customer")
public class DeleteCustomerServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    public DeleteCustomerServlet() {
        super();
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        CustomerServices customerServices = new CustomerServices(request, response);
        customerServices.deleteCustomer();
    }

}

src/com/bookstore/controller/admin/customer/EditCustomerServlet.java
package com.bookstore.controller.admin.customer;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.CustomerServices;

@WebServlet("/admin/edit_customer")
public class EditCustomerServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    public EditCustomerServlet() {
        super();
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        CustomerServices customerServices = new CustomerServices(request, response);
        customerServices.editCustomer();
    }

}

WebContent/common/common_order_detail.jsp
<div class="row">
	<div class="col-sm-2"></div>
	
	<div class="col-sm-8">
		<div class="card">
			<div class="card-header">
				<div class="text-center"><h3>Order Overview:</h3></div>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col"><b>Ordered By: </b></div>
					<div class="col">${order.customer.fullname}</div>
				</div>
				<div class="row">
					<div class="col"><b>Order Status: </b></div>
					<div class="col">${order.status}</div>
				</div>
				<div class="row">
					<div class="col"><b>Order Date: </b></div>
					<div class="col">${order.orderDate}</div>
				</div>
				<div class="row">
					<div class="col"><b>Payment Method: </b></div>
					<div class="col">${order.paymentMethod}</div>
				</div>						
				<div class="row">
					<div class="col"><b>Book Copies: </b></div>
					<div class="col">${order.bookCopies}</div>
				</div>
				<div class="row">
					<div class="col"><b>Total Amount: </b></div>
					<div class="col"><fmt:formatNumber value="${order.total}" type="currency" /></div>
				</div>			
			</div>
		</div>
		
		<div class="row">&nbsp;</div>
		
		<div class="card">
			<div class="card-header">
				<div class="text-center"><h3>Recipient Information:</h3></div>
			</div>
			<div class="card-body">
				<div class="row">
					<div class="col"><b>First Name: </b></div>
					<div class="col">${order.firstname}</div>
				</div>
				<div class="row">
					<div class="col"><b>Last Name: </b></div>
					<div class="col">${order.firstname}</div>
				</div>			
				<div class="row">
					<div class="col"><b>Phone: </b></div>
					<div class="col">${order.phone}</div>
				</div>
				<div class="row">
					<div class="col"><b>Address Line 1: </b></div>
					<div class="col">${order.addressLine1}</div>
				</div>
				<div class="row">
					<div class="col"><b>Address Line 2: </b></div>
					<div class="col">${order.addressLine1}</div>
				</div>					
				<div class="row">
					<div class="col"><b>City: </b></div>
					<div class="col">${order.city}</div>
				</div>
				<div class="row">
					<div class="col"><b>State: </b></div>
					<div class="col">${order.state}</div>
				</div>
				<div class="row">
					<div class="col"><b>Country: </b></div>
					<div class="col">${order.countryName}</div>
				</div>
				<div class="row">
					<div class="col"><b>Zipcode: </b></div>
					<div class="col">${order.zipcode}</div>
				</div>				
			</div>
		</div>
		
		<div class="row">&nbsp;</div>
		
		<div class="card">
			<div class="card-header">
				<div class="text-center"><h3>Ordered Books:</h3></div>
			</div>
			<div class="card-body">
				<c:forEach items="${order.orderDetails}" var="orderDetail" varStatus="status">
					<div class="row">
						<div class="col-sm">${status.index + 1}</div>
						<div class="col-5"><img width="128" height="164" src="data:image/jpg;base64,${orderDetail.book.base64Image}" /></div>
						<div class="col-6">
							<div><h6>${orderDetail.book.title}</h6></div>
							<div>by <i>${orderDetail.book.author}</i></div>
							<div><fmt:formatNumber value="${orderDetail.book.price}" type="currency" /></div>								
							<div>									
								X ${orderDetail.quantity}
							</div>
							<div>= <b><fmt:formatNumber	value="${orderDetail.subtotal}" type="currency" /></b></div>									
						</div>								
					</div>
					<div class="row">&nbsp;</div>				
				</c:forEach>
			</div>
		</div>
		
		<div class="row">&nbsp;</div>
		
		<div class="card">
			<div class="card-header">
				<div class="text-center"><h3>Summary:</h3></div>
			</div>
			<div class="card-body">
				<div class="col text-center">
					<p>Subtotal: <fmt:formatNumber value="${order.subtotal}" type="currency" /></p>
					<p>Tax: <fmt:formatNumber value="${order.tax}" type="currency" /></p>
					<p>Shipping Fee: <fmt:formatNumber value="${order.shippingFee}" type="currency" /></p>
					<p>TOTAL: <fmt:formatNumber value="${order.total}" type="currency" /></p>				
				</div>
			</div>
		</div>						
	</div>
	
	<div class="col-sm-2"></div>
</div>

WebContent/common/customer_form.jsp
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">E-mail:</label>
				<div class="col-sm-8">
					<input type="email" name="email" class="form-control" value="${customer.email}" required minlength="5" maxlength="64" />
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">First Name:</label>
				<div class="col-sm-8">
					<input type="text" name="firstname" class="form-control" value="${customer.firstname}" required minlength="2" maxlength="30" />
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Last Name:</label>
				<div class="col-sm-8">
					<input type="text" name="lastname" class="form-control" value="${customer.lastname}" required minlength="2" maxlength="30"/>
				</div>
			</div>			
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Password:</label>
				<div class="col-sm-8">
					<input type="password" id="password" name="password" class="form-control" value="${customer.password}" required minlength="5" maxlength="16" />
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Confirm Password:</label>
				<div class="col-sm-8">
					<input type="password" name="confirmPassword" class="form-control" 
							value="${customer.password}" required minlength="5" maxlength="16"
							oninput="checkPasswordMatch(this)" />
				</div>
			</div>			
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Phone Number:</label>
				<div class="col-sm-8">
					<input type="text" name="phone" class="form-control" value="${customer.phone}" required minlength="9" maxlength="15"/>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Address Line 1:</label>
				<div class="col-sm-8">
					<input type="text" name="address1" class="form-control" value="${customer.addressLine1}" required minlength="10" maxlength="128"/>
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Address Line 2:</label>
				<div class="col-sm-8">
					<input type="text" name="address2" class="form-control" value="${customer.addressLine2}" required maxlength="128"/>
				</div>
			</div>			
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">City:</label>
				<div class="col-sm-8">
					<input type="text" name="city" class="form-control" value="${customer.city}" required minlength="2" maxlength="32" />
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">State:</label>
				<div class="col-sm-8">
					<input type="text" name="state" class="form-control" value="${customer.state}" required minlength="2" maxlength="45" />
				</div>
			</div>			
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Zip Code:</label>
				<div class="col-sm-8">
					<input type="text" name="zipCode" class="form-control" value="${customer.zipcode}" required minlength="3" maxlength="24" />
				</div>
			</div>
			<div class="form-group row">
				<label class="col-sm-4 col-form-label">Country:</label>
				<div class="col-sm-8">
					<select name="country" required class="form-control">
					<c:forEach items="${mapCountries}" var="country">
						<option value="${country.value}" <c:if test='${customer.country eq country.value}'>selected='selected'</c:if> >${country.key}</option>
					</c:forEach>
					</select>
					
				</div>
			</div>																
			<div class="row">&nbsp;</div>
			<div class="row">
				<div class="col text-center">
					<button type="submit" class="btn btn-primary mr-3">Save</button>
					<input type="button" value="Cancel" class="btn btn-secondary" onclick="history.go(-1);" />
				</div>
			</div>				