src/com/bookstore/entity/Book.java
package com.bookstore.entity;
// Generated May 22, 2018 5:46:15 AM by Hibernate Tools 5.2.10.Final

import java.util.Base64;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;
import javax.swing.event.TreeSelectionEvent;

/**
 * Book generated by hbm2java
 */
@Entity
@Table(name = "book", catalog = "bookstoredb", uniqueConstraints = @UniqueConstraint(columnNames = "title"))
@NamedQueries({
		@NamedQuery(name = "Book.findAll", query = "SELECT b FROM Book b"),
        @NamedQuery(name = "Book.findByTitle", query = "SELECT b FROM Book b WHERE b.title = :title"),
        @NamedQuery(name = "Book.countAll", query = "SELECT COUNT(*) FROM Book b"),
        @NamedQuery(name = "Book.countByCategory", query = "SELECT COUNT(b) FROM Book b " + "WHERE b.category.categoryId = :catId"),
        @NamedQuery(name = "Book.findByCategory", query = "SELECT b FROM Book b JOIN " + "Category c ON b.category.categoryId = c.categoryId AND c.categoryId = :catId"),
        @NamedQuery(name = "Book.listNew", query = "SELECT b FROM Book b ORDER BY b.publishDate DESC"),
        @NamedQuery(name = "Book.search", query = "SELECT b FROM Book b WHERE b.title LIKE '%' || :keyword || '%'" + " OR b.author LIKE '%' || :keyword || '%'" + " OR b.description LIKE '%' || :keyword || '%'")
		})
public class Book implements java.io.Serializable {

    private Integer bookId;
    private Category category;
    private String title;
    private String author;
    private String description;
    private String isbn;
    private byte[] image;
    private String base64Image;
    private float price;
    private Date publishDate;
    private Date lastUpdateTime;
    private Set<Review> reviews = new HashSet<Review>(0);
    private Set<OrderDetail> orderDetails = new HashSet<OrderDetail>(0);

    public Book() {
    }

    public Book(Integer bookId) {
        super();
        this.bookId = bookId;
    }


    public Book(Category category, String title, String author, String description, String isbn, byte[] image, float price, Date publishDate, Date lastUpdateTime) {
        this.category = category;
        this.title = title;
        this.author = author;
        this.description = description;
        this.isbn = isbn;
        this.image = image;
        this.price = price;
        this.publishDate = publishDate;
        this.lastUpdateTime = lastUpdateTime;
    }

    public Book(Category category, String title, String author, String description, String isbn, byte[] image, float price, Date publishDate, Date lastUpdateTime, Set<Review> reviews, Set<OrderDetail> orderDetails) {
        this.category = category;
        this.title = title;
        this.author = author;
        this.description = description;
        this.isbn = isbn;
        this.image = image;
        this.price = price;
        this.publishDate = publishDate;
        this.lastUpdateTime = lastUpdateTime;
        this.reviews = reviews;
        this.orderDetails = orderDetails;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "book_id", unique = true, nullable = false)
    public Integer getBookId() {
        return this.bookId;
    }

    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "category_id", nullable = false)
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @Column(name = "title", unique = true, nullable = false, length = 128)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "author", nullable = false, length = 64)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    @Column(name = "description", nullable = false, length = 16777215)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "isbn", nullable = false, length = 15)
    public String getIsbn() {
        return this.isbn;
    }

    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    @Column(name = "image", nullable = false)
    public byte[] getImage() {
        return this.image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    @Column(name = "price", nullable = false, precision = 12, scale = 0)
    public float getPrice() {
        return this.price;
    }

    public void setPrice(float price) {
        this.price = price;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "publish_date", nullable = false, length = 10)
    public Date getPublishDate() {
        return this.publishDate;
    }

    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_update_time", nullable = false, length = 19)
    public Date getLastUpdateTime() {
        return this.lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "book")
    public Set<Review> getReviews() {
        TreeSet<Review> sortedReviews = new TreeSet<>(new Comparator<Review>() {

            @Override
            public int compare(Review review1, Review review2) {
                return review2.getReviewTime().compareTo(review1.getReviewTime());
            }

        });

        sortedReviews.addAll(reviews);
        return sortedReviews;
    }

    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "book")
    public Set<OrderDetail> getOrderDetails() {
        return this.orderDetails;
    }

    public void setOrderDetails(Set<OrderDetail> orderDetails) {
        this.orderDetails = orderDetails;
    }

    @Transient
    public String getBase64Image() {
        this.base64Image = Base64.getEncoder().encodeToString(this.image);
        return this.base64Image;
    }

    @Transient
    public void setBase64Image(String base64Image) {
        this.base64Image = base64Image;
    }

    @Transient
    public float getAverageRating() {
        float averageRating = 0.0f;
        float sum = 0.0f;

        if (reviews.isEmpty()) {
            return 0.0f;
        }

        for (Review review : reviews) {
            sum += review.getRating();
        }

        averageRating = sum / reviews.size();

        return averageRating;
    }

    @Transient
    public String getRatingStars() {
        float averageRating = getAverageRating();

        return getRatingString(averageRating);
    }

    @Transient
    public String getRatingString(float averageRating) {
        String result = "";

        int numberOfStarsOn = (int) averageRating;

        for (int i = 1; i <= numberOfStarsOn; i++) {
            result += "on,";
        }

        int next = numberOfStarsOn + 1;

        if (averageRating > numberOfStarsOn) {
            result += "half,";
            next++;
        }

        for (int j = next; j <= 5; j++) {
            result += "off,";
        }

        return result.substring(0, result.length() - 1);
    }


    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((bookId == null) ? 0 : bookId.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Book other = (Book) obj;
        if (bookId == null) {
            if (other.bookId != null) return false;
        } else if (!bookId.equals(other.bookId)) return false;
        return true;
    }

}

src/com/bookstore/entity/Customer.java
package com.bookstore.entity;
// Generated May 22, 2018 5:46:15 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Locale;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "bookstoredb", uniqueConstraints = @UniqueConstraint(columnNames = "email"))
@NamedQueries({@NamedQuery(name = "Customer.findAll", query = "SELECT c FROM Customer c ORDER BY c.registerDate DESC"), @NamedQuery(name = "Customer.findByEmail", query = "SELECT c FROM Customer c WHERE c.email = :email"), @NamedQuery(name = "Customer.countAll", query = "SELECT COUNT(c.email) FROM Customer c"), @NamedQuery(name = "Customer.checkLogin", query = "SELECT c FROM Customer c WHERE c.email = :email AND c.password = :pass")})
public class Customer implements java.io.Serializable {

    private Integer customerId;
    private String email;
    private String firstname;
    private String lastname;
    private String addressLine1;
    private String addressLine2;
    private String city;
    private String state;
    private String country;
    private String phone;
    private String zipcode;
    private String password;
    private Date registerDate;
    private Set<Review> reviews = new HashSet<Review>(0);
    private Set<BookOrder> bookOrders = new HashSet<BookOrder>(0);

    public Customer() {
    }

    public Customer(String email, String firstname, String lastname, String address1, String address2, String city, String state, String country, String phone, String zipcode, String password, Date registerDate) {
        this.email = email;
        this.firstname = firstname;
        this.lastname = lastname;
        this.addressLine1 = address1;
        this.addressLine2 = address2;
        this.city = city;
        this.state = state;
        this.country = country;
        this.phone = phone;
        this.zipcode = zipcode;
        this.password = password;
        this.registerDate = registerDate;
    }

    public Customer(String email, String firstname, String lastname, String address1, String address2, String city, String state, String country, String phone, String zipcode, String password, Date registerDate, Set<Review> reviews, Set<BookOrder> bookOrders) {
        this(email, firstname, lastname, address1, address2, city, state, country, phone, zipcode, password, registerDate);
        this.reviews = reviews;
        this.bookOrders = bookOrders;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "customer_id", unique = true, nullable = false)
    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    @Column(name = "email", unique = true, nullable = false, length = 64)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "firstname", nullable = false, length = 30)
    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @Transient
    public String getFullname() {
        return this.firstname + " " + this.lastname;
    }

    @Column(name = "lastname", nullable = false, length = 30)
    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }


    @Column(name = "address_line1", nullable = false, length = 128)
    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String address1) {
        this.addressLine1 = address1;
    }

    @Column(name = "address_line2", nullable = false, length = 128)
    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String address2) {
        this.addressLine2 = address2;
    }

    @Column(name = "city", nullable = false, length = 32)
    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    @Column(name = "state", nullable = false, length = 45)
    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "country", nullable = false, length = 4)
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Transient
    public String getCountryName() {
        return new Locale("", this.country).getDisplayCountry();
    }

    @Column(name = "phone", nullable = false, length = 15)
    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Column(name = "zipcode", nullable = false, length = 24)
    public String getZipcode() {
        return this.zipcode;
    }

    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    @Column(name = "password", nullable = false, length = 16)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "register_date", nullable = false, length = 19)
    public Date getRegisterDate() {
        return this.registerDate;
    }

    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
    public Set<Review> getReviews() {
        return this.reviews;
    }

    public void setReviews(Set<Review> reviews) {
        this.reviews = reviews;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
    public Set<BookOrder> getBookOrders() {
        return this.bookOrders;
    }

    public void setBookOrders(Set<BookOrder> bookOrders) {
        this.bookOrders = bookOrders;
    }

}

src/com/bookstore/controller/admin/review/DeleteReviewServlet.java
package com.bookstore.controller.admin.review;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.ReviewServices;

@WebServlet("/admin/delete_review")
public class DeleteReviewServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    public DeleteReviewServlet() {
        super();
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        ReviewServices reviewServices = new ReviewServices(request, response);
        reviewServices.deleteReview();
    }

}

src/com/bookstore/controller/admin/review/EditReviewServlet.java
package com.bookstore.controller.admin.review;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.ReviewServices;

@WebServlet("/admin/edit_review")
public class EditReviewServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    public EditReviewServlet() {
        super();
    }

    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        ReviewServices reviewServices = new ReviewServices(request, response);
        reviewServices.editReview();
    }

}

src/com/bookstore/controller/frontend/book/SearchBookServlet.java
package com.bookstore.controller.frontend.book;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.bookstore.service.BookServices;

@WebServlet("/search")
public class SearchBookServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	public SearchBookServlet() {
	}

	@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		BookServices bookServices = new BookServices(request, response);
		bookServices.search();
	}

}

WebContent/frontend/book_rating.jsp
<c:forTokens items="${book.ratingStars}" delims="," var="star">
	<c:if test="${star eq 'on'}">
		<img src="images/rating_on.png" />
	</c:if>
	<c:if test="${star eq 'off'}">
		<img src="images/rating_off.png" />
	</c:if>
	<c:if test="${star eq 'half'}">
		<img src="images/rating_half.png" />
	</c:if>
</c:forTokens>

WebContent/frontend/books_list_by_category.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>    
<!DOCTYPE html>
<html>
	<jsp:include page="page_head.jsp">
		<jsp:param name="pageTitle" value="Books in ${category.name}" />
	</jsp:include>
<body>
<div class="container">
	<jsp:directive.include file="header.jsp" />
	
	<div class="row">
		<div class="col text-center"><h2>${category.name}</h2></div>
	</div>
	
	<div>&nbsp;</div>
	
	<div class="row">
	<c:forEach items="${listBooks}" var="book">
		<jsp:directive.include file="book_group.jsp" />		
	</c:forEach>
	</div>
	
	<jsp:directive.include file="footer.jsp" />
</div>	
</body>
</html>

WebContent/frontend/customer_profile.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
	<jsp:include page="page_head.jsp">
		<jsp:param name="pageTitle" value="Customer Profile" />
	</jsp:include>
<body>
<div class="container">
	<jsp:directive.include file="header.jsp" />
	
	<div class="row">
		<div class="col text-center"><h3>Welcome, ${loggedCustomer.fullname}</h3></div>
	</div>		
			
	<div class="row">
		<div class="col-sm-3"></div>
		
		<div class="col-sm-6">
			<div class="row">
				<div class="col"><b>E-mail Address:</b></div>
				<div class="col">${loggedCustomer.email}</div>
			</div>
			
			<div class="row">
				<div class="col"><b>First Name:</b></div>
				<div class="col">${loggedCustomer.firstname}</div>
			</div>
					
			<div class="row">
				<div class="col"><b>Last Name:</b></div>
				<div class="col">${loggedCustomer.lastname}</div>
			</div>
		
			<div class="row">
				<div class="col"><b>Phone Number:</b></div>
				<div class="col">${loggedCustomer.phone}</div>
			</div>
		
			<div class="row">
				<div class="col"><b>Address Line 1:</b></div>
				<div class="col">${loggedCustomer.addressLine1}</div>
			</div>
		
			<div class="row">
				<div class="col"><b>Address Line 2:</b></div>
				<div class="col">${loggedCustomer.addressLine2}</div>
			</div>
												
			<div class="row">
				<div class="col"><b>City:</b></div>
				<div class="col">${loggedCustomer.city}</div>
			</div>
			
			<div class="row">
				<div class="col"><b>State:</b></div>
				<div class="col">${loggedCustomer.state}</div>
			</div>
						
			<div class="row">
				<div class="col"><b>Zip Code:</b></div>
				<div class="col">${loggedCustomer.zipcode}</div>
			</div>
						
			<div class="row">
				<div class="col"><b>Country:</b></div>
				<div class="col">${loggedCustomer.countryName}</div>
			</div>
				
			<div class="row">&nbsp;</div>
			
			<div class="row">
				<div class="col text-center"><b><a href="edit_profile">Edit My Profile</a></b></div>
			</div>		
		</div>
		
		<div class="col-sm-3"></div>
	</div>
	
	<jsp:directive.include file="footer.jsp" />
</div>
</body>
</html>

WebContent/frontend/footer.jsp
<div>&nbsp;</div>
<div class="row text-center">
	<div class="col mb-3 mt-4">
		<h4>Copyright (C) 2018 by Evergreen Books Co., Ltd</h4>
		<a href="about">About Us</a> |
		<a href="contact">Contact Us</a> |
		<a href="policy">Privacy Policy</a> |
		<a href="shipping">Shipping & Delivery</a>
	</div>
</div>

WebContent/frontend/header.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div class="row">
	<a href="${pageContext.request.contextPath}/">
		<img src="images/BookstoreLogo.png" class="img-fluid" />
	</a>
</div>

<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNavbar">
		<span class="navbar-toggler-icon"></span>
	</button>
	
	<div class="collapse navbar-collapse" id="topNavbar">
		<form action="search" method="get" class="form-inline">
			<input type="search" name="keyword" class="form-control mr-sm-2 mt-1" placeholder="keyword"/>
			<input type="submit" value="Search" class="btn btn-outline-success mt-1" />	
		</form>
		<ul class="navbar-nav">
			<c:if test="${loggedCustomer == null}">
				<li class="nav-item">
					<a href="login" class="nav-link">Sign In</a>
				</li>
				<li class="nav-item">
					<a href="register" class="nav-link">Register</a>
				</li>			
			</c:if>
			
			<c:if test="${loggedCustomer != null}">
				<li class="nav-item">
					<a href="view_profile" class="nav-link">Welcome, ${loggedCustomer.fullname}</a>
				</li>
				
				<li class="nav-item">
					<a href="view_orders" class="nav-link">My Orders</a>
				</li>
				
				<li class="nav-item">
					<a href="logout" class="nav-link">Logout</a>
				</li>
			</c:if>
			
			<li class="nav-item">
				<a href="view_cart" class="nav-link">Cart</a>
			</li>			
		</ul>
	</div>
</nav>

<div>&nbsp;</div>
<div class="row justify-content-center">
	<c:forEach var="category" items="${listCategory}" varStatus="status">
		<a href="view_category?id=${category.categoryId}">
			<font size="+1"><b><c:out value="${category.name}" /></b></font>
		</a>
		<c:if test="${not status.last}">
		&nbsp; | &nbsp;
		</c:if>
	</c:forEach>
</div>

WebContent/frontend/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
	<jsp:include page="page_head.jsp">
		<jsp:param name="pageTitle" value="Evergreen Books" />
	</jsp:include>
<body>
<div class="container">

	<jsp:directive.include file="header.jsp" />
	
	<div class="row text-center">
		<div class="col"><h2>New Books:</h2></div>
	</div>
	
	<div class="row justify-content-center mb-3">
		<c:forEach items="${listNewBooks}" var="book">
				<jsp:directive.include file="book_group.jsp" />
		</c:forEach>	
	</div>
	
	<div class="row text-center">
		<div class="col"><h2>Best-Selling Books:</h2></div>
	</div>	
	
	<div class="row justify-content-center mb-3">
		<c:forEach items="${listBestSellingBooks}" var="book">
			<jsp:directive.include file="book_group.jsp" />
		</c:forEach>	
	</div>
	
	<div class="row text-center">
		<div class="col"><h2>Most-favored Books:</h2></div>
	</div>	
	
	<div class="row justify-content-center mb-3">
		<c:forEach items="${listFavoredBooks}" var="book">
			<jsp:directive.include file="book_group.jsp" />
		</c:forEach>	
	</div>
	
	<jsp:directive.include file="footer.jsp" />
</div>	
</body>
</html>

WebContent/frontend/review_form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
	<title>Write a Review - Online Book Store</title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
	<script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>
</head>
<body>
<div class="container">
	<jsp:directive.include file="header.jsp" />
	
	<form action="submit_review" method="post" style="max-width: 800px; margin: 0 auto">
			<div class="row">
				<div class="col"><h2>Your Reviews</h2></div>
				<div class="col">&nbsp;</div>
				<div class="col"><h4>${loggedCustomer.fullname}</h4></div>
			</div>
			<div class="row">
				<div class="col"><hr/></div>
			</div>
			<div class="row">
				<div class="col-sm">
					<h4>${book.title}</h4>
					<img class="img-fluid" src="data:image/jpg;base64,${book.base64Image}" />
				</div>
				<div class="col-sm">
					<div id="rateYo"></div>
					<input type="hidden" id="rating" name="rating" />
					<input type="hidden" name="bookId" value="${book.bookId}" />
					<div>&nbsp;</div>
					<div>
						<input type="text" name="headline" class="form-control" 
							placeholder="Headline or summary for your review (required)" required minlength="10" maxlength="128" />
					</div>
					<div>&nbsp;</div>
					<div>
						<textarea name="comment" cols="70" rows="10" class="form-control" 
							placeholder="Write your review details..." required minlength="10" maxlength="500" ></textarea>
					</div>
				</div>
			</div>
			<div>&nbsp;</div>
			<div class="row">
				<div class="col text-center">
					<button type="submit" class="btn btn-primary">Submit</button>
					&nbsp;&nbsp;
					<button type="button" onclick="history.go(-1)" class="btn btn-secondary">Cancel</button>
				</div>
			</div>
	</form>
	
	<jsp:directive.include file="footer.jsp" />
</div>
<script type="text/javascript">

	$(document).ready(function() {
		
		$("#rateYo").rateYo({
			starWidth: "40px",
			fullStar: true,
			onSet: function (rating, rateYoInstance) {
				$("#rating").val(rating);
			}
		});		
	});
</script>	
</body>
</html>